name: Build & Artifact

on:
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: '17'
      distribution: 'oracle'
   - run: mvn --batch-mode  --update-snapshots verify 
   - run: mkdir test && cp target/*.jar test
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.6.2
     with:
       name: Package
       path: test
